// <auto-generated />
namespace MyHotel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class NewCostpropertyinOrdermodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewCostpropertyinOrdermodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201912092244093_New Cost property in Order model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
